<a href="https://colab.research.google.com/github/reshin94/eda_iris_classification/blob/master/Machine_Learning_Using_scikit_learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [185]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler,Normalizer,OneHotEncoder
import numpy as np

iris=load_iris()
normalizer = Normalizer(norm='l2').fit(iris.data)
iris_normalized = normalizer.transform(iris.data)
print(iris_normalized.mean(axis=0))
onehotencoder = OneHotEncoder()
iris_target_onehot = onehotencoder.fit_transform(iris.target.reshape(-1,1))
print(iris_target_onehot.toarray()[[0,50,100]])

[0.75140029 0.40517418 0.45478362 0.14107142]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [187]:
from sklearn.impute import SimpleImputer
#from sklearn.preprocessing import Imputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(iris.data)
iris_imputed = imputer.transform(iris.data)
print(iris_imputed.mean(axis=0))

[5.84333333 3.05733333 3.758      1.19933333]


In [170]:
from sklearn.datasets import load_iris
import numpy as np
from sklearn.preprocessing import StandardScaler,Normalizer,OneHotEncoder,Imputer
iris=load_iris()
normalizer = Normalizer(norm='l2').fit(iris.data)
iris_normalized = normalizer.transform(iris.data)
print(iris_normalized.mean(axis=0))
onehotencoder = OneHotEncoder()
iris_target_onehot = onehotencoder.fit_transform(iris.target.reshape(-1,1))
print(iris_target_onehot.toarray()[[0,50,100]])
imputer=Imputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(iris.data)
iris_imputed = imputer.transform(iris.data)
print(iris_imputed.mean(axis=0))